### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jeffreyca84** [iDebugAll/nextbox-ui-plugin#118]
Installation on Ubuntu 22.04....followed the Netbox YouTube installation video from JS to the letter...

Running into an issue trying to install the plugin on a fresh install of Netbox.

root@netbox-vm1:/opt/netbox/netbox# source /opt/netbox/venv/bin/activate
(venv) root@netbox-vm1:/opt/netbox/netbox# pip3 install nextbox-ui-plugin
Collecting nextbox-ui-plugin
  Downloading nextbox_ui_plugin-0.11.0.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: nextbox-ui-plugin
  Building wheel for nextbox-ui-plugin (setup.py) ... done
  Created wheel for nextbox-ui-plugin: filename=nextbox_ui_plugin-0.11.0-py3-none-any.whl size=1256535 sha256=152823a41487b659246f70e789dccd9b3be75e8c2049ae340030901409198d83
  Stored in directory: /root/.cache/pip/wheels/2a/cb/0a/be0d97de5af2e26fb1e040f1dbfb42c4fb7dfd1c5c8f64be94
Successfully built nextbox-ui-plugin
Installing collected packages: nextbox-ui-plugin
Successfully installed nextbox-ui-plugin-0.11.0
(venv) root@netbox-vm1:/opt/netbox/netbox# deactivate 
root@netbox-vm1:/opt/netbox/netbox# cd netbox/
root@netbox-vm1:/opt/netbox/netbox/netbox# vim configuration.py 
root@netbox-vm1:/opt/netbox/netbox/netbox# source /opt/netbox/venv/bin/activate
(venv) root@netbox-vm1:/opt/netbox/netbox/netbox# cd /opt/netbox/netbox/
(venv) root@netbox-vm1:/opt/netbox/netbox# python3 manage.py collectstatic
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 259, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 662, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_ui_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 266, in fetch_command
    settings.INSTALLED_APPS
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 665, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox_ui_plugin: Module not found. Check that the plugin module has been installed within the correct Python environment.

**Comment by iDebugAll** [comment]
> ModuleNotFoundError: No module named 'netbox_ui_plugin'

The correct plugin name is ```nextbox_ui_plugin```. Fix it in your enabled plugins list and it should work.

**Comment by jeffreyca84** [comment]
Thank you so much.  I can't believe it was just that simple typo!
