### ISSUE TITLE
Error: 'Interface' object does not support indexing

### ISSUE THREAD

**Issue by n0emis** [iDebugAll/nextbox-ui-plugin#34]
Due to the change in cable tracing (https://github.com/netbox-community/netbox/issues/4900), this plugin is currently incompatible with Netbox-Version 2.10.x.

When opening the Topology-View the following error get's thrown:
```
Internal Server Error: /plugins/nextbox-ui/site_topology/1/
Traceback (most recent call last):
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/nextbox_ui_plugin/views.py", line 334, in get
    topology_dict, device_roles, multi_cable_connections, device_tags = get_site_topology(site_id)
  File "/home/n0emis/.nc/Documents/_unsortiert/programmieren/netbox/.venv/lib/python3.9/site-packages/nextbox_ui_plugin/views.py", line 311, in get_site_topology
    if isinstance(cable_path[0][0], Interface) and isinstance(cable_path[-1][2], Interface):
TypeError: 'Interface' object is not subscriptable
```

**Comment by iDebugAll** [comment]
@n0emis thank you for a detailed report. I have published a quickfix to workaround this issue. Please try to update to the latest plugin version.
Some corner cases with multi-cable connections through patch panels (see #32) are still relevant. But the general layout works fine according to my tests.
