### ISSUE TITLE
[Docker on K8s] ModuleNotFoundError: No module named 'nextbox_ui_plugin'

### ISSUE THREAD

**Issue by MaxRink** [iDebugAll/nextbox-ui-plugin#49]
Im using the provided Dockerfile to install the plugin into my container. As a base image ive tried lastest-ldap and v2.10.5, both produce the same issue for me.
```
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'rqworker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 592, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nextbox_ui_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 595, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin nextbox_ui_plugin: Module not found. Check that the plugin module has been installed within the correct Python environment.
```

ive tried forcing the venv with "RUN source /opt/netbox/venv/bin/activate" to no avail
The plugin config is set to "['nextbox_ui_plugin',] ", as documented
Im not overwriting any dir in the venv or overwriting env vars

Thus im basically out if ideas why it isnt working.

**Comment by iDebugAll** [comment]
Does `docker build` show some errors during the plugin installations steps?
Does your app definition point to the newly built image name?

**Comment by MaxRink** [comment]
nope, no errors
```Status: Downloaded newer image for artifactory.devops.telekom.de/hub.docker.com/netboxcommunity/netbox:latest-ldap
 ---> c2731f754dae
Step 5/10 : RUN source /opt/netbox/venv/bin/activate
 ---> Running in 63b0f88af03e
Removing intermediate container 63b0f88af03e
 ---> 5c86df45ff44
Step 6/10 : COPY ./nextbox_ui_plugin /source/nextbox-ui-plugin/nextbox_ui_plugin/
 ---> a52b7bb2e968
Step 7/10 : COPY ./setup.py /source/nextbox-ui-plugin/
 ---> ef0b49dde612
Step 8/10 : COPY ./MANIFEST.in /source/nextbox-ui-plugin/
 ---> faec76f1b80c
Step 9/10 : COPY ./README.md /source/nextbox-ui-plugin/
 ---> 6300b4a8cdeb
Step 10/10 : RUN pip3 install --no-cache-dir nextbox-ui-plugin
 ---> Running in 2bf65f79225c
Collecting nextbox-ui-plugin
  Downloading nextbox_ui_plugin-0.8.0.tar.gz (1.0 MB)
Using legacy 'setup.py install' for nextbox-ui-plugin, since package 'wheel' is not installed.
Installing collected packages: nextbox-ui-plugin
    Running setup.py install for nextbox-ui-plugin: started
    Running setup.py install for nextbox-ui-plugin: finished with status 'done'
Successfully installed nextbox-ui-plugin-0.8.0
Removing intermediate container 2bf65f79225c
 ---> b1b995bde67d
Successfully built b1b995bde67d
Successfully tagged registry.devops.telekom.de/maximilian.rink/nextbox-ui-plugin:rebase
```
only notable deviation is me pulling the netbox image through a caching registry to avoid docker-hub rate limits. the iamge is the same as from docker hub directly tho ( same Image ID)

And im using the correct image, with the pull policy set to always
```
    Image:          harbor.sce-dcn.net/schiff-public/nextbox-ui-plugin:rebase
    Image ID:       harbor.sce-dcn.net/schiff-public/nextbox-ui-plugin@sha256:56b8f66d236fc0ca767e37a56c1ad97c21a21d4be7759612f3094bb860386785
```
looking in my registry at the same image ID i can see that RUN pip3 install --no-cache-dir nextbox-ui-plugin has run in the docker build of that image

**Comment by MaxRink** [comment]
so, ive solved it by adding 
```
ENV VIRTUAL_ENV=/opt/netbox/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
```
the venv wasnt used by pip

**Comment by MaxRink** [comment]
after that i unfortunatelyy found another bug:
it seems like the container doesnt run collectstatic by default anymore, thus the static files never get served.
In addition you mostly want to run the container with a read-only filesystem by default, which prevents the static files from being created at startup
It would propably be the best ideo to statically link them at container build as they are linked to the plugin version anyway

**Comment by iDebugAll** [comment]
Thank you for detailed analysis.
Would you like to prepare a PR based on you input above?

**Comment by MaxRink** [comment]
Sure :)
